name: Build

on: workflow_dispatch

defaults:
  run:
    working-directory: .

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: 'setup'
        uses: actions/checkout@v2
      - name: 'Setup GCC'
        uses: Dup4/actions-setup-gcc@v1
        with:
          version: latest
      - name: 'Build'    
        run: gcc -O1 SD_Unlocker.c -o SD_Unlocker
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: SD_Unlocker
          path: SD_Unlocker
          retention-days: 5